name: Deploy Snowpark UDFs and Stored Procs

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'
          cache: 'pip'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run tests
        run: python -m pytest 
      
      - name: Create deployment artifact
        run:  zip -r my-project.zip . -x venv/\* .git/\* 
      
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: python-app
          path: '${{ github.workspace }}/my-project.zip'
  
  deploy:
    runs-on: ubuntu-latest
    needs: build
    env:
      SNOWSQL_ACCOUNT: '<REPLACE: your account id>'
      SNOWSQL_USER: '<REPLACE: your username>'
      SNOWSQL_DATABASE: '<REPLACE: your database>'
      SNOWSQL_SCHEMA: '<REPLACE: your public>'
      SNOWSQL_WAREHOUSE: '<REPLACE: your warehouse>'
      SNOWSQL_PWD: ${{ secrets.SNOWSQL_PWD }}

    steps:
      - uses: actions/checkout@v3

      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: python-app

      - name: Install SnowSQL
        run: |
          curl -O https://sfc-repo.snowflakecomputing.com/snowsql/bootstrap/1.2/linux_x86_64/snowsql-1.2.24-linux_x86_64.bash
          SNOWSQL_DEST=~/snowflake SNOWSQL_LOGIN_SHELL=~/.profile bash snowsql-1.2.24-linux_x86_64.bash

      - name: Deploy jobs
        run: ~/snowflake/snowsql -f resources.sql
